

create type color as enum(
    'Color1',
    'Color2',
    'Color3',
    'Color4',
    'Color5',
    'Color6',
    'Color7',
    'Color8',
    'Color9',
    'Color10',
    'Color11' ,
    'Color12'
    
);


create type product as enum(
     'Product1',
    'Product2',
    'Product3',
    'Product4',
    'Product5',
    'Product6',
    'Product7',
    'Product8',
    'Product9',
    'Product10',
    'Product11' ,
    'Product12',
    'Product13',
    'Product14',
    'Product15',
    'Product16' ,
    'Product17'
);


create type phase as enum(
    'In Production', 
    'Produced', 
    'In Stock'
);



CREATE TABLE IF NOT EXISTS orders (
    order_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    color color NOT NULL,
    product product NOT NULL,
    amount INTEGER NOT NULL,
    prty_lvl INTEGER NOT NULL,
    phase phase NOT NULL
);